<?php

/**
 * @file
 * Examples demonstrating how to implement and invoke hooks.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function yse_sageboy_help($route_name, RouteMatchInterface $route_match) {
  if ($route_name == 'help.page.yse_sageboy') {
    $text = file_get_contents(__DIR__ . '/README.md');
    if (!Drupal::moduleHandler()->moduleExists('markdown')) {
      return '<pre>' . $text . '</pre>';
    }
    else {
      /** @var \Drupal\markdown\PluginManager\ParserManagerInterface $parser_manager */
      $parser_manager = \Drupal::service('plugin.manager.markdown.parser');
      $parser = $parser_manager->getDefaultParser([
        'render_strategy' => ['type' => 'none'],
      ]);
      return $parser->parse($text);
    }
  }
  return NULL;
}


/**
 * Implements hook_form_FORM_ID_alter().
 */
function yse_sageboy_form_user_login_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // should wire in settings for accessform_msg and classes
  $accessform_msg = 'Værsågod, Sageboy Kroonsdòttir.';
  $form['#prefix'] = '<div class="grid-container"><h3>' . $accessform_msg . '</h3>';
  $form['#suffix'] = '</div>';
}
